modLoader="javafml"
loaderVersion="[33,)"
issueTrackerURL="https://github.com/TheIllusiveC4/CulinaryConstruct/issues"
logoFile="${mod_icon}"
license="LGPL-3.0-or-later"
[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
displayURL="${mod_url}"
authors="${mod_author}"
description='''
${mod_description}
'''
[[dependencies.culinaryconstruct]]
    modId="forge"
    mandatory=true
    versionRange="[33,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.culinaryconstruct]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.2,1.17)"
    ordering="NONE"
    side="BOTH"